# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "undobug"
repo_name: "audio-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/audio-arxiv-daily.json'
json_gitpage_path: './docs/audio-arxiv-daily-web.json'
json_wechat_path: './docs/audio-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Audio":
        filters: [
            "Speech interaction", "Speech Synthesis", "TTS", "Text to speech", "Music Generation", "Speech to Speech",
            "Speech-driven", "Audio Generation", "Speech Generation", "Neural TTS", "Audio LLM", "Audio large language model" ]
