name: Run Arxiv Papers Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */5 * *"

env:
  GITHUB_USER_NAME: audio365
  GITHUB_USER_EMAIL: fyb1126@163.com
  
jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    if: github.actor == 'audio365'  # 只有 audio365 触发时才执行

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv
          pip install requests
          pip install pyyaml
          
      - name: Run daily arxiv 
        run: |
          python daily_arxiv.py
          
      - name: Push new audio-arxiv-daily.md
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Github Action Automatic Update audio Arxiv Papers"
          files: README.md docs/audio-arxiv-daily.json docs/audio-arxiv-daily-web.json docs/index.md docs/audio-arxiv-daily-wechat.json docs/wechat.md
          rebase: 'true'
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
